apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/joekleinsorge/freshlab.git
        revision: main
        directories:
          - path: apps/*
  template:
    metadata:
      name: '{{ `{{path.basename}}` }}'
    spec:
      destination:
        name: in-cluster
        namespace: '{{ `{{path.basename}}` }}'
      project: default
      source:
        repoURL: https://github.com/joekleinsorge/freshlab.git
        path: apps/*
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 16m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true