ombi:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        ombi.io/enable: 'true'
        hajimari.io/appName: Ombi
        hajimari.io/icon: basket-fill
      hosts:
        - host: &host requests.kleinsorge.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: ombi-tls-certificate
          hosts:
            - *host
  persistence:
    config:
      enabled: true
      type: nfs
      server: 192.168.1.208
      path: /volume1/kube/ombi
  env:
    PUID: "1030"
    PGID: "101"
