firefly-iii:
  persistence:
    enabled: true
    storageClassName: "nfs-client"
    accessModes: ReadWriteOnce
    storage: 1Gi
  config:
    env:
      DB_HOST: "firefly-db"
      DB_CONNECTION: pgsql
      DB_PORT: "5432"
      DB_DATABASE: firefly
      DB_USERNAME: firefly
      DEFAULT_LANGUAGE: "en_US"
      DEFAULT_LOCALE: "equal"
      TZ: "New_York/America"
      TRUSTED_PROXIES: "**"
  secrets:
    env:
      APP_PASSWORD: "CHANGE_ENCRYPT_ME"
      DB_PASSWORD: "CHANGE_ENCRYPT_ME"
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: firefly-iii
        hajimari.io/icon: tabler:pig-money
      hosts:
        - host: &host money.kleinsorge.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: firefly-iii-tls-certificate
          hosts:
            - *host
