firefly-iii:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: firefly-iii
        hajimari.io/icon: savings
      hosts:
        - host: &host money.kleinsorge.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: firefly-iii-tls-certificate
          hosts:
            - *host
  env:
    SITE_OWNER: lab@kleinsorge.dev
    TZ: America/New_York
    DB_CONNECTION: mysql
    DB_HOST: db
    DB_PORT: 3306
    DB_DATABASE: firefly
    DB_USERNAME: firefly
    DB_PASSWORD: secret_firefly_password
  persistence:
    config:
      enabled: true
      type: nfs
      server: 192.168.1.208
      path: /volume1/kube/firefly-iii
  mariadb:
   enabled: true
   password: "secret_firefly_password"
