firefly-iii:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: firefly-iii
        hajimari.io/icon: tabler:pig-money
      hosts:
        - host: &host money.kleinsorge.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: firefly-iii-tls-certificate
          hosts:
            - *host
  env:
    SITE_OWNER: lab@kleinsorge.dev
    TZ: America/New_York
    # DB_CONNECTION: mysql
    # DB_HOST: db
    # DB_PORT: 3306
    # DB_DATABASE: "firefly"
    # DB_USERNAME: "firefly"
    # DB_PASSWORD: secret_firefly_password
  # mariadb:
  #  enabled: true
  #  username: "firefly"
  #  rootPassword: secret_firefly_password
  #  password: secret_firefly_password
  #  database: "firefly"
spec:
  template:
    spec:
      containers:
        volumeMounts:
          - name: nfs-pvc
            mountPath: /
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: nfs-client
