apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-plex-config-pv
spec:
  capacity:
    storage: 100G
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.208
    path: /volume1/kube/kube-plex
