apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: plex
  name: plex-data-pvc
spec:
  accessModes:
    - ReadOnlyMany
  volumeName: plex-data-pv
  resources:
    requests:
      storage: 20Ti
  storageClassName: ""  
