apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: plex
  labels:
    app: plexserver
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: plexserver
  strategy:
    rollingUpdate:
      maxSurge: 0 
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: plexserver
    spec:
      volumes:
      - name: plex-config
        persistentVolumeClaim:
          claimName: plex-config-pvc
      - name: plex-data
        persistentVolumeClaim:
          claimName: plex-data-pvc
      containers:
      - env:
        - name: PUID
          value: "\x49\x48\x51\x48"
        - name: PGID
          value: "\x49\x48\x49"
        - name: PLEX_CLAIM
          value: claim-CYxbDeJd-GFZTHKYFrex
        - name: ADVERTISE_IP
          value: https://plex.kleinsorge.dev
        - name: HOSTNAME
          value: plex.kleinsorge.dev
        - name: ALLOWED_NETWORKS
          value: 192.168.0.0/16
        - name: TZ
          value: America/New_York
        - name: VERSION
          value: latest
        image: ghcr.io/linuxserver/plex 
        imagePullPolicy: Always
        name: plexserver
        ports:
        - containerPort: 32400     # < required network portnumber. See https://hub.docker.com/r/linuxserver/plex
          name: pms-web            # < reference name from the port in the service yaml
          protocol: TCP
        - containerPort: 32469
          name: dlna-tcp
          protocol: TCP
        - containerPort: 1900
          name: dlna-udp
          protocol: UDP
        - containerPort: 3005
          name: plex-companion
          protocol: TCP  
        - containerPort: 5353
          name: discovery-udp
          protocol: UDP  
        - containerPort: 8324
          name: plex-roku
          protocol: TCP  
        - containerPort: 32410
          name: gdm-32410
          protocol: UDP
        - containerPort: 32412
          name: gdm-32412
          protocol: UDP
        - containerPort: 32413
          name: gdm-32413
          protocol: UDP
        - containerPort: 32414
          name: gdm-32414
          protocol: UDP
        resources: {}
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /config
          name: plex-config
        - mountPath: /data
          name: plex-data
        restartPolicy: Always