apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    hajimari.io/appName: plex 
    hajimari.io/icon: video 
  labels:
    app.kubernetes.io/instance: plex 
  name: plex
  namespace: plex
spec:
  ingressClassName: nginx
  rules:
    - host: plex.kleinsorge.dev
      http:
        paths:
          - backend:
              service:
                name: plex 
                port:
                  name: http
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - plex.kleinsorge.dev
      secretName: plex-tls-certificate
