apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: plex            
  namespace: plex      
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"  
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/app-root: /web             
spec:
  rules:
  - host: plex.kleinsorge.dev
    http:
      paths:
      - path: /
        backend:
          serviceName: plex-tcp
          servicePort: pms-web
  tls:
  - hosts:
    - plex.kleinsorge.dev
    secretName: plex.kleinsorge.dev-tls

