apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-media-automation
  namespace: plex
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: plex
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: seerr
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: tautulli
