apiVersion: v1
kind: PersistentVolume
metadata: 
  name: plex-data-pv
spec:
  storageClassName: ""
  capacity:
    storage: 10Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.208
    path: /volume1/Media
