apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: plex
  name: plex-config-pvc
spec:
  storageClassName: ""
  volumeName: plex-config-pv
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
