apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config-pv
spec:
  storageClassName: ""
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.208
    path: /volume1/kube/plex
