apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-plex-pv
spec:
  capacity:
    storage: 10Ti
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-plex
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /volume1/Media
    server: 192.168.1.208