apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app: plex
    app.kubernetes.io/instance: plex
    app.kubernetes.io/name: plex
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: plex-media-server-0.3.0
  name: plex
  namespace: plex
