apiVersion: v1
kind: Service
metadata:
  labels:
    app: plex
    app.kubernetes.io/instance: plex
    app.kubernetes.io/name: plex
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: plex-media-server-0.3.0
  name: plex
  namespace: plex
spec:
  ports:
    - name: pms
      port: 32400
      protocol: TCP
      targetPort: 32400
  selector:
    app.kubernetes.io/instance: plex
    app.kubernetes.io/name: plex
  type: ClusterIP
