image:
  repository: plexinc/pms-docker
  tag: plexpass
  pullPolicy: Always
kubePlex:
  resources: {}
    # Limits and requests that are applied to the kube-plex transcoding pod. Can
    # be used to request GPU instances for pods as well as normal Kubernetes
    # limits.
    # requests:
    #   cpu: 100m
    #   "gpu.intel.com/i915: 1
    # limits:
    #   "gpu.intel.com/i915: 1
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx    
    cert-manager.io/cluster-issuer: letsencrypt-prod
    hajimari.io/enable: 'true'
    hajimari.io/appName: 'plex'
    hajimari.io/icon: 'plex'
  hosts:
    - plex.kleinsorge.dev
  tls:
    - secretName: plex-tls-certificate
      hosts:
        - plex.kleinsorge.dev
claimToken: "claim-FfC8xtkWwg1JiwwYqsCZ"
timezone: "America/New_York"
extraEnv: 
    ADVERTISE_IP: 'https://plex.kleinsorge.dev'
    ALLOWED_NETWORKS: '192.168.0.0/16,10.0.0.0/8'
    PLEX_PREFERENCE_1: 'FriendlyName=plexonk8s'
  # puid: 1002
  # pgid: 1002
  # NVIDIA_VISIBLE_DEVICES: all
  # NVIDIA_DRIVER_CAPABILITIES: video,compute,utility
persistence:
  data:
    claimName: "plex-data-pvc"
  config:
    claimName: "plex-config-pvc"
