plex:
  image:
    repository: linuxserver/plex
    tag: latest
    pullPolicy: IfNotPresent  
  env:
    TZ: 'America/New_York'
    PLEX_CLAIM: 'claim-aKy1sjfyNWuEz2XyS25q'
    # ADVERTISE_IP: 'https://plex.kleinsorge.dev'
    # ALLOWED_NETWORKS: '192.168.0.0/16,10.0.0.0/8'
    # PLEX_PREFERENCE_1: 'FriendlyName=plexonk8s'
    # PLEX_PREFERENCE_2: 'LanNetworksBandwidth=192.168.0.0/16,10.0.0.0/8'
    # PLEX_PREFERENCE_3: "logDebug=0"
  # ingress:
  #   main:
  #     enabled: true
  #     ingressClassName: nginx
  #     annotations:
  #       cert-manager.io/cluster-issuer: letsencrypt-prod
  #       hajimari.io/enable: 'true'
  #       hajimari.io/appName: 'plex'
  #       hajimari.io/icon: 'plex'
  #     hosts:
  #       - host: &host plex.kleinsorge.dev
  #         paths:
  #           - path: /
  #             pathType: Prefix
  #     tls:
  #       - secretName: plex-tls-certificate
  #         hosts:
  #           - *host
  service:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/allow-shared-ip: plex-svc
    port:
      port: 32400
      targetPort: 32400
  persistence:
    data:
      enabled: true
      existingClaim: "plex-data-pvc"
    config:
      enabled: true
      existingClaim: "plex-config-pvc"
  hostNetwork: true
  resources: {}
  podAnnotations: {}
  proxy:
    enable: false