haste-server:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: paste
        hajimari.io/icon: material-symbols:content-copy
      hosts:
        - host: &host paste.kleinsorge.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: haste-server-tls-certificate
          hosts:
            - *host