apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system
helmCharts:
- name: ingress-nginx
  includeCRDs: true
  version: 4.0.18
  repository: https://kubernetes.github.io/ingress-nginx
