apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: cluster.local/nfs-nfs-subdir-external-provisioner
  creationTimestamp: "2023-05-26T19:02:36Z"
  finalizers:
  - ""
  name: pvc-05af82f1-240d-47ff-9829-436fe992fb9f
  resourceVersion: "70514887"
  uid: 6e2faf15-113c-4cef-9507-150acdf831dd
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100G
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: photoprism-config-pvc
    namespace: photoprism
    resourceVersion: "70514880"
    uid: 05af82f1-240d-47ff-9829-436fe992fb9f
  nfs:
    path: /volume1/kube/photoprism-photoprism-config-pvc-pvc-05af82f1-240d-47ff-9829-436fe992fb9f
    server: 192.168.1.208
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs-client
  volumeMode: Filesystem
status:
  phase: Bound
