apiVersion: v1
kind: ConfigMap
metadata:
  name: freshlab-grafana-datasources
  namespace: {{ .Release.Namespace }}
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: http://kube-prometheus-stack-prometheus.kube-prometheus-stack:9090
        access: proxy
        jsonData:
          httpMethod: POST
          timeInterval: 30s
      - name: Loki
        type: loki
        uid: Loki
        url: http://loki.loki:3100
        access: proxy
      - name: Tempo
        type: tempo
        uid: Tempo
        url: http://tempo.tempo:3200
        access: proxy
        jsonData:
          httpMethod: GET
