apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: actions-runner
spec:
  replicas: 1
  template:
    spec:
      repository: joekleinsorge/freshlab
      image: summerwind/actions-runner
      serviceAccountName: github-runner
      automountServiceAccountToken: true
