external-dns:
  provider: cloudflare
  txtOwnerId: freshlab
  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-api-token-secret
          key: api-token
  extraArgs:
    - --annotation-filter=external-dns.alpha.kubernetes.io/exclude notin (true)

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
