node-feature-discovery:
  master:
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
  worker:
    config: |-
      {
        "core": {
          "sleepInterval": "5m",
          "labelSources": ["cpu", "kernel", "memory", "network", "pci", "storage", "system"]
        }
      }
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
