apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: budget-data
spec:
  storageClassName: ""
  volumeName: budget-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
