apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kiali-ambient
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: kiali
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 15008
        - protocol: TCP
          port: 20001
        - protocol: TCP
          port: 9090
