---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-kleinsorge-dev
  namespace: traefik
spec:
  secretName: traefik-kleinsorge-dev-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.kleinsorge.dev"
  dnsNames:
  - "kleinsorge.dev"
  - "*.kleinsorge.dev"
