apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frigate
  namespace: frigate
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: frigate
      app.kubernetes.io/name: frigate
