apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runners
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: arc-runners
spec:
  project: default 
  sources:
    - chart: gha-runner-scale-set
      repoURL: 'ghcr.io/actions/actions-runner-controller-charts'
      targetRevision: 0.9.3
      helm:
        valueFiles:
          - $values/values.yaml
    - repoURL: 'https://github.com/joekleinsorge/freshlab.git'
      targetRevision: main 
      ref: platform/runners/values
  destination:
    name: in-cluster
    namespace: arc-runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Replace=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: "apps"
      kind: "Deployment"
      jsonPointers:
        - /spec/template/spec/containers/0/resources
