apiVersion: v2
name: runners 
version: 0.0.0
dependencies:
  - name: gha-runner-scale-set
    version: 0.9.0
    repository: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
 
 
