node-red:
  image:
    repository: nodered/node-red
    tag: 2.2.3-12-minimal
  env:
    TZ: "America/Chicago"
    FLOWS: "flows.json"
    NODE_RED_ENABLE_PROJECTS: "true"
    NODE_RED_ENABLE_SAFE_MODE: "false"
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: vault-issuer
        cert-manager.io/common-name: node-red.rsr.net
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy.kube-system.svc.cluster.local:80/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: https://auth.rsr.net/oauth2/start
      hosts:
        - host: node-red.rsr.net
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "node-red.rsr.net"
          secretName: node-red-cert
