paperless:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Paperless
        hajimari.io/icon: file-document
      hosts:
        - host: &host paperless.kleinsorge.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: paperless-tls-certificate
          hosts:
            - *host
  postgresql:
    enabled: true
  # persistence:
  #   data:
  #     enabled: true
  #     type: nfs
  #     server: 192.168.1.208
  #     path: /volume1/kube/paperless/data
  #   media:
  #     enabled: true
  #     type: nfs
  #     server: 192.168.1.208
  #     path: /volume1/kube/paperless/media
