  hosts: metal
  roles:
    - { role: automatic_upgrade, tags: [always] }
    - { role: disable_selinux, tags: [always] }
    - { role: disable_firewalld, tags: [always] }
    - { role: disable_swap, tags: [always] }
    - { role: mount_nfs, tags: [always] }

- name: Create Kubernetes cluster
  hosts: metal
  roles:
    - { role: k3s, tags: [always] }

- name: Create some basic config
  hosts: localhost
  environment:
    KUBECONFIG: ./kubeconfig.yaml
  roles:
    - { role: metallb_config, tags: [always] }
