- name: Setup Operating system
  hosts: metal
  roles:
    - automatic_upgrade

- name: Create Kubernetes cluster
  hosts: metal
  roles:
    - k3s

- name: Create some basic config
  hosts: localhost
  environment:
    KUBECONFIG: ./kubeconfig.yaml
  roles:
    - metallb_config
