---
- import_playbook: prepare.yml

- name: Create Kubernetes cluster
  hosts: metal
  become: true
  roles:
    - k3s

- name: Install Kubernetes addons
  hosts: localhost
  environment:
    KUBECONFIG: "{{ playbook_dir }}/kubeconfig.yaml"
  roles:
    - cilium
