- name: Setup Operating system
  hosts: metal
  roles:
    - prerequisites
    - coreos_config
    - coreos_updates
    - mount_nfs

- name: Create Kubernetes cluster
  hosts: metal
  roles:
    - k3s

- name: Install Kubernetes addons
  hosts: localhost
  environment:
    KUBECONFIG: ./kubeconfig.yaml
  roles:
    - cilium
