- name: Setup Operating system
  hosts: metal
  roles:
    - prerequisites
    - automatic_upgrade
    - disable_selinux
    - disable_firewalld
    - disable_swap
    - limit_logs
    - mount_nfs

- name: Create Kubernetes cluster
  hosts: metal
  roles:
    - k3s

- name: Install Kubernetes addons
  hosts: localhost
  environment:
    KUBECONFIG: ./kubeconfig.yaml
  roles:
    - cilium

# - name: Create some basic config
#   hosts: localhost
#   environment:
#     KUBECONFIG: ./kubeconfig.yaml
#   roles:
#     - metallb_config
