- name: Teardown Kubernetes cluster
  hosts: metal
  tasks:
  - name: Stop k3s service
    systemd:
      name: k3s
      state: stopped
    ignore_errors: true

  - name: Run k3s uninstall script
    shell: |
      if [ -f /usr/local/bin/k3s-uninstall.sh ]; then
        /usr/local/bin/k3s-uninstall.sh
      fi
    ignore_errors: true

  - name: Cleanup CNI configurations
    shell: |
      rm -rf /etc/cni/net.d/*
      rm -rf /var/lib/cni/
    ignore_errors: true

  - name: Remove k3s data directories
    shell: |
      rm -rf /var/lib/rancher
      rm -rf /var/lib/longhorn
      rm -rf /var/lib/kubelet
      rm -rf /etc/rancher
    ignore_errors: true

  - name: Clean up iptables
    shell: |
      iptables -F
      iptables -X
      ip6tables -F
      ip6tables -X
    ignore_errors: true

  - name: Kill any remaining k3s processes
    shell: |
      pkill -9 -f k3s || true
    ignore_errors: true

  - name: Remove systemd service files
    shell: |
      rm -f /etc/systemd/system/k3s*.service
      systemctl daemon-reload
    ignore_errors: true

  - name: Reboot system
    reboot:
    ignore_errors: true