searxng:
  env:
    INSTANCE_NAME: "search"
    BASE_URL: "https://search.kleinsorge.dev"
    AUTOCOMPLETE: "false"
  persistence:
    config:
      enabled: true 
  ingress:
    main:
      enabled: true 
      ingressclassname: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: 'true'
      hosts:
        - host: &host search.kleinsorge.dev
          paths:
            - path: /
              pathtype: prefix
      tls:
        - secretname: search-tls-certificate
          hosts:
            - *host
  redis:
    enabled: true
  
