hajimari:
  image:
    tag: v0.2.0
  env:
    TZ: America/New_York
  hajimari:
    defaultEnable: true
    namespaceSelector:
      any: true
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: 'false'
      hosts:
        - host: &host home.kleinsorge.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: hajimari-tls-certificate
          hosts:
            - *host
  hajimari:
    defaultEnable: true
    namespaceSelector:
      any: true
    name: "Joey"
    groups:
      - name: Homelab
        links:
          - name: GitHub repository
            url: https://github.com/joeykleinsorge/homelab
