hajimari:
  env:
    TZ: America/New_York
  persistence:
    data:
      enabled: false
  ingress:
    main:
      enabled: true
      ingressClassName: istio
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: 'false'
      hosts:
        - host: &host home.kleinsorge.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: hajimari-tls-certificate
          hosts:
            - *host
  hajimari:
    name: Joe
    title: Home
    lightTheme: chalk
    darkTheme: horizon
    showAppUrls: true
    showAppInfo: true
    showAppStatus: true
    customThemes:
      - name: danger
        backgroundColor: '#0c0e0c'
        primaryColor: '#eaebea'
        accentColor: '#d8323c'
    defaultEnable: true
    namespaceSelector:
      any: true
    customApps:
      - group: Applications
        apps:
          - name: Actual Budget
            url: https://budget.kleinsorge.dev
            icon: wallet
          - name: Argo CD
            url: https://argocd.kleinsorge.dev
            icon: kubernetes
          - name: Argo Workflows
            url: https://workflows.kleinsorge.dev
            icon: source-branch
          - name: Authelia
            url: https://authelia.kleinsorge.dev
            icon: shield-account
          - name: Dex
            url: https://dex.kleinsorge.dev
            icon: key-chain
          - name: Disney Alerts
            url: https://disney-alerts.kleinsorge.dev
            icon: ticket
          - name: Excalidraw
            url: https://draw.kleinsorge.dev
            icon: pencil
          - name: Flask Cache
            url: https://flask.kleinsorge.dev
            icon: flask
          - name: FreshRSS
            url: https://rss.kleinsorge.dev
            icon: rss
          - name: Frigate
            url: https://frigate.kleinsorge.dev
            icon: cctv
          - name: Grafana
            url: https://grafana.kleinsorge.dev
            icon: simple-icons:grafana
          - name: Grocy
            url: https://grocy.kleinsorge.dev
            icon: cart
          - name: Immich
            url: https://photos.kleinsorge.dev
            icon: simple-icons:immich
          - name: Kindle Weather
            url: https://kindle-weather.kleinsorge.dev
            icon: weather-partly-cloudy
          - name: KitchenOwl
            url: https://kitchenowl.kleinsorge.dev
            icon: food-apple
          - name: Kiali
            url: https://kiali.kleinsorge.dev
            icon: topology
          - name: Kube Ops View
            url: https://view.kleinsorge.dev
            icon: kubernetes
          - name: LibreSpeed
            url: https://speed.kleinsorge.dev
            icon: speedometer
          - name: Mealie
            url: https://mealie.kleinsorge.dev
            icon: silverware-fork-knife
          - name: NGINX Web
            url: https://web.kleinsorge.dev
            icon: nginx
          - name: Plex
            url: https://plex.kleinsorge.dev
            icon: plex
          - name: Seafile
            url: https://files.kleinsorge.dev
            icon: simple-icons:seafile
          - name: Tools
            url: https://tools.kleinsorge.dev
            icon: tools
          - name: Uptime Kuma
            url: https://status.kleinsorge.dev
            icon: pulse
    globalBookmarks:
      - group: Homelab
        bookmarks:
          - name: Public GitHub repository
            url: https://github.com/joekleinsorge/freshlab
          - name: Hardware
            url: https://192.168.1.101:9090
