metal:
  children:
    masters:
      hosts:
        vm1: {ansible_host: 192.168.2.1, disk: sda, network_interface: ens18}
        vm2: {ansible_host: 192.168.2.2, disk: sda, network_interface: ens18}
        vm3: {ansible_host: 192.168.2.3, disk: sda, network_interface: ens18}
