metal:
  children:
    masters:
      hosts:
        metal1: {ansible_host: 192.168.1.101, disk: sda, network_interface: ens18}
        metal2: {ansible_host: 192.168.1.102, disk: sda, network_interface: ens18}
        metal3: {ansible_host: 192.168.1.103, disk: sda, network_interface: ens18}
        
