rook-ceph:
  monitoring:
    enabled: true
rook-ceph-cluster:
  monitoring:
    enabled: true
    createPrometheusRules: true
  cephClusterSpec:
    mon:
      count: 1
      allowMultiplePerNode: true
    mgr:
      count: 1
    dashboard:
      ssl: false
      enabled: true
      port: 7000
    crashCollector:
      disable: false
    logCollector:
      enabled: false
    removeOSDsIfOutAndSafeToRemove: true
    storage:
      useAllNodes: true
      useAllDevices: false
      config:
        osdsPerDevice: "1"
      storageClassDeviceSets:
        - name: set1
          count: 1
          portable: false
          tuneSlowDeviceClass: false
          volumeClaimTemplates:
            - metadata:
                name: data
              spec:
                resources:
                  requests:
                    storage: 10Gi
                storageClassName: standard-rwo
                volumeMode: Block
                accessModes:
                  - ReadWriteOnce
    resources:
      mgr:
        limits:
          memory: "1Gi"
        requests:
          cpu: "100m"
          memory: "512Mi"
      mon:
        limits:
          memory: "1Gi"
        requests:
          cpu: "100m"
          memory: "100Mi"
      osd:
        limits:
          memory: "2Gi"
        requests:
          cpu: "100m"
          memory: "512Mi"
  cephBlockPools:
    - name: standard-rwo
      spec:
        replicated:
          size: 1
          requireSafeReplicaSize: false
      storageClass:
        enabled: true
        name: standard-rwo
        isDefault: true
        allowVolumeExpansion: true
        parameters:
          imageFeatures: layering,fast-diff,object-map,deep-flatten,exclusive-lock
          csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
          csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
          csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
          csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
  cephBlockPoolsVolumeSnapshotClass:
    enabled: true
    isDefault: true
  cephFileSystems:
    - name: standard-rwx
      spec:
        metadataPool:
          replicated:
            size: 1
            requireSafeReplicaSize: false
        dataPools:
          - name: data0
            replicated:
              size: 1
              requireSafeReplicaSize: false
        metadataServer:
          activeCount: 1
          activeStandby: true
          resources:
            limits:
              memory: "4Gi"
            requests:
              cpu: "100m"
              memory: "100Mi"
          priorityClassName: system-cluster-critical
      storageClass:
        enabled: true
        name: standard-rwx
        isDefault: false
        allowVolumeExpansion: true
        pool: data0
        parameters:
          csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
          csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
          csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
          csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
  cephFileSystemVolumeSnapshotClass:
    enabled: true
    isDefault: false
  cephObjectStores: []
