rook-ceph:
  monitoring:
    enabled: true
  enableDiscoveryDaemon: false
  csi:
    enableCephfsSnapshotter: true
    enableRbdSnapshotter: true
    enableCephfsDriver: true
    enableRbdDriver: true
    provisionerTolerations:
      - operator: "Exists"
    pluginTolerations:
      - operator: "Exists"
    volumeReplication:
      enabled: false
    csiRBDProvisionerResource: |
      - name: csi-provisioner
        resource:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 200m
    csiRBDPluginResource: |
      - name: driver-registrar
        resource:
          requests:
            memory: 128Mi
            cpu: 50m
          limits:
            memory: 256Mi
            cpu: 100m
      - name: csi-rbdplugin
        resource:
          requests:
            memory: 512Mi
            cpu: 250m
          limits:
            memory: 1Gi
            cpu: 500m
rook-ceph-cluster:
  monitoring:
    enabled: true
    createPrometheusRules: true
  cephClusterSpec:
    mon:
      count: 3
    mgr:
      count: 2
    dashboard:
      ssl: false
    logCollector:
      enabled: false
    removeOSDsIfOutAndSafeToRemove: true
    resources:
      mgr:
        limits:
          memory: "1Gi"
        requests:
          cpu: "100m"
          memory: "512Mi"
      mon:
        limits:
          memory: "2Gi"
        requests:
          cpu: "100m"
          memory: "100Mi"
      osd:
        limits:
          memory: "4Gi"
        requests:
          cpu: "100m"
          memory: "512Mi"
  cephBlockPools: []
  cephBlockPoolsVolumeSnapshotClass:
    enabled: true
    isDefault: true
    annotations:
      snapshot.storage.kubernetes.io/is-default-class: "true"
    parameters:
      clusterID: "{{ .Release.Namespace }}"
      csi.storage.k8s.io/snapshotter-secret-name: rook-csi-rbd-provisioner
      csi.storage.k8s.io/snapshotter-secret-namespace: "{{ .Release.Namespace }}"
    driver: rook-ceph.rbd.csi.ceph.com
    deletionPolicy: Delete
  cephFileSystems: []
  cephFileSystemVolumeSnapshotClass:
    enabled: true
    isDefault: false
    annotations:
      snapshot.storage.kubernetes.io/is-default-class: "false"
    parameters:
      clusterID: "{{ .Release.Namespace }}"
      csi.storage.k8s.io/snapshotter-secret-name: rook-csi-cephfs-provisioner
      csi.storage.k8s.io/snapshotter-secret-namespace: "{{ .Release.Namespace }}"
    driver: rook-ceph.cephfs.csi.ceph.com
    deletionPolicy: Delete
  cephObjectStores: []

snapshot-controller:
  replicaCount: 2
  webhook:
    enabled: true
    certDir: /tmp/k8s-webhook-server/serving-certs
    failurePolicy: Fail
    timeoutSeconds: 2
    # Disable certificate validation for the webhook
    certManager:
      enabled: false
    service:
      annotations: {}
    # Use self-signed certificates
    certificates:
      create: true
      caBundle: ""
      server:
        create: true
      certKeySize: 2048
      duration: 8760h
      renewBefore: 360h
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi
