dex:
  image:
    tag: v2.45.1
  config:
    issuer: https://dex.kleinsorge.dev
    storage:
      type: kubernetes
      config:
        inCluster: true
    oauth2:
      skipApprovalScreen: true
    enablePasswordDB: true
    staticPasswords:
      - email: admin@kleinsorge.dev
        hashFromEnv: DEX_ADMIN_PASSWORD_HASH
        username: admin
        name: Freshlab Administrator
        preferredUsername: admin
        emailVerified: true
        groups:
          - freshlab-admins
        userID: "1"
    staticClients:
      - id: grafana-sso
        name: Grafana
        redirectURIs:
          - 'https://grafana.kleinsorge.dev/login/generic_oauth'
        secretEnv: GRAFANA_SSO_CLIENT_SECRET
      - id: argocd-sso
        name: Argo CD
        redirectURIs:
          - 'https://argocd.kleinsorge.dev/auth/callback'
        secretEnv: ARGOCD_SSO_CLIENT_SECRET
      - id: argo-workflows-sso
        name: Argo Workflows
        redirectURIs:
          - 'https://workflows.kleinsorge.dev/oauth2/callback'
        secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
  envFrom:
    - secretRef:
        name: dex-secrets
  ingress:
    enabled: true
    className: istio
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: Dex
      hajimari.io/icon: mdi:key-chain
    hosts:
      - host: &host dex.kleinsorge.dev
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: dex-tls-certificate
        hosts:
          - *host
