seafile:
  ingress:
    main:
      enabled: true
      ingressClassName: istio
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Seafile
        hajimari.io/icon: simple-icons:seafile
      hosts:
        - host: &host files.kleinsorge.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: seafile-tls-certificate
          hosts:
            - *host
  mariadb:
    enabled: true
    image:
      registry: docker.io
      repository: bitnamilegacy/mariadb
      tag: 10.6.8-debian-11-r9
    primary:
      persistence:
        enabled: true
        storageClass: longhorn
        size: 10Gi
  persistence:
    data:
      enabled: true
      type: nfs
      server: 192.168.1.208
      path: /volume1/kube/seafile
