vault:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: vault
      hajimari.io/icon: account
    hosts:
      - host: &host vault.kleinsorge.dev
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: vault-tls-certificate
        hosts:
          - *host
