vault:
  server:
    config: |
      ui = true
      listener "tcp" {
        tls_disable     = 1
        address         = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      # storage "s3" {
      #   bucket     = "vault-backend"
      #   endpoint   = "http://minio.minio.svc.cluster.local:9000"
      #   region     = "us-k3d-1"
      #   access_key = "minio"
      #   secret_key = "password"
      #   disable_ssl = "true"
      #   s3_force_path_style = true
      # }
      service_registration: "kubernetes"
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hajimari.io/appName: "vault"
        hajimari.io/icon: "pencil"
      hosts:
        - host: &host "vault.kleinsorge.dev"
          paths:
            - path: "/"
              pathType: "Prefix"
      tls:
        - secretName: "vault-tls-certificate"
          hosts:
            - *host
    ui:
      enabled: true
      serviceType: "ClusterIP"
      serviceNodePort: null
      externalPort: 8200
