apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-nfs
spec:
  storageClassName: immich-nfs
  capacity:
    storage: 1Mi
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.208
    path: /volume1/Media/Memories
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-nfs
  namespace: immich
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: immich-nfs
  resources:
    requests:
      storage: 1Mi
