apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-pvc
spec:
  storageClassName: ""
  volumeName: immich-pv
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Ti
