immich:
  immich:
    persistence:
      library:
        existingClaim: "immich-nfs"
  postgresql:
    enabled: true
    image:
      repository: tensorchord/pgvecto-rs
      tag: pg14-v0.1.11
    global:
      postgresql:
        auth:
          username: immich
          database: immich
          password: password
    primary:
      initdb:
        scripts:
          create-extensions.sql: |
            CREATE EXTENSION cube;
            CREATE EXTENSION earthdistance;
            CREATE EXTENSION vectors;
  redis:
    enabled: true 
  server:
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          hajimari.io/appName: "Immich"
          hajimari.io/icon: "heroicons:photo"
        hosts:
          - host: "immich.kleinsorge.dev"
            paths:
              - path: "/"
                pathType: "Prefix"
        tls:
          - secretName: "immich-tls-certificate"
            hosts:
              - "immich.kleinsorge.dev"
