immich:
  controllers:
    main:
      containers:
        main:
          probes:
            startup:
              enabled: true
              spec:
                timeoutSeconds: 10
                failureThreshold: 180
            liveness:
              enabled: true
              spec:
                timeoutSeconds: 10
            readiness:
              enabled: true
              spec:
                timeoutSeconds: 10
          env:
            TZ: America/New_York
            IMMICH_HOST: 0.0.0.0
            DB_HOSTNAME: immich-postgres
            DB_PORT: 5432
            DB_USERNAME: immich
            DB_DATABASE_NAME: immich
            DB_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: immich-db
                  key: postgres-password

  immich:
    metrics:
      enabled: true
    persistence:
      library:
        existingClaim: immich-library

  server:
    controllers:
      main:
        pod:
          labels:
            istio.io/dataplane-mode: none
        containers:
          main:
    persistence:
      media:
        enabled: true
        type: nfs
        server: 192.168.1.208
        path: /volume1/Media
        globalMounts:
          - path: /media
            readOnly: true
    ingress:
      main:
        enabled: false
        ingressClassName: istio
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          hajimari.io/appName: Immich
          hajimari.io/icon: simple-icons:immich
        hosts:
          - host: &host photos.kleinsorge.dev
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: immich-tls-certificate
            hosts:
              - *host

  machine-learning:
    controllers:
      main:
        pod:
          labels:
            istio.io/dataplane-mode: none
        containers:
          main:

  valkey:
    enabled: true
