immich:
  repository:
    name: immich-charts
    url: https://github.com/immich-app/immich-charts
  env:
    DB_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: immich-secrets
          key: password
    JWT_SECRET:
      valueFrom:
        secretKeyRef:
          name: immich-secrets
          key: JWT_SECRET

  proxy:
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          hajimari.io/appName: "Immich"
          hajimari.io/icon: heroicons:photo
        hosts:
          - host: &host immich.kleinsorge.dev
            paths:
              - path: /

        tls:
          - secretName: immich-tls-certificate
            hosts:
              - *host
    service:
      main:
        enabled: true
        type: LoadBalancer
        ports:
          http:
            port: 8080
  redis:
    enabled: true
  postgresql:
    enabled: true
    global:
      postgresql:
        auth:
          existingSecret: immich-secrets
  immich:
    persistence:
      library:
        enabled: true
        existingClaim: immich-nfs
        mountPath: /usr/src/app/upload
  typesense:
    enabled: true
    env:
      TYPESENSE_DATA_DIR: /tsdata
      TYPESENSE_API_KEY: 
        valueFrom:
          secretKeyRef:
            name: immich-secrets
            key: TYPESENSE_API_KEY
    persistence:
      tsdata:
        enabled: true
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn
  resources:
    requests:
      cpu: 100m
      memory: 250Mi
    limits:
      memory: 6000Mi

