immich:
  immich:
    persistence:
      library:
        enabled: true
        existingClaim: immich-nfs
        mountPath: /usr/src/app/upload
  postgresql:
    enabled: true 
    global:
      postgresql:
        auth:
          username: immich
          database: immich
          password: immich
  redis:
    enabled: true 
  typesense:
    enabled: true 
    persistence:
      tsdata:
        enabled: false
  server:
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          hajimari.io/appName: "Immich"
          hajimari.io/icon: "heroicons:photo"
        hosts:
          - host: "immich.kleinsorge.dev"
            paths:
              - path: "/"
                pathType: "Prefix"
        tls:
          - secretName: "immich-tls-certificate"
            hosts:
              - "immich.kleinsorge.dev"
