---
immich:
  immich:
    persistence:
      library:
        existingClaim: immich-pvc
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Immich
        hajimari.io/icon: filmstrip
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hosts:
        - host: immich.kleinsorge.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: immich-tls-certificate
          hosts:
            - immich.kleinsorge.dev

