apiVersion: v1
kind: Secret
metadata:
    name: dex-secrets
    namespace: dex
type: Opaque
stringData:
    KANIDM_CLIENT_ID: ENC[AES256_GCM,data:V1A+KYVTEcvnKw==,iv:KzRIdQqnohRHICbdkBdOrMmRewyr8wkUN5ca7gLg8v8=,tag:B7ZdNnUdMMaFtnwLaq/UDg==,type:str]
    KANIDM_CLIENT_SECRET: ENC[AES256_GCM,data:fdsMtH9Mm/RpvQ==,iv:7DhPD0i8uUa4sQh2kZFFHUZ5dn6FQtuIR1kZDbho3RM=,tag:O/6DZu6OILKYngiO4XRkxw==,type:str]
    GRAFANA_SSO_CLIENT_SECRET: ENC[AES256_GCM,data:OJRqDYFv3Fn4QNwfbEtUTOgBmw==,iv:7Gbq3zSzME669kMoyVt/nFggz+p3bTmb8z8gax+FU1E=,tag:YqlEPAMQkpe8aKd8EZSpYg==,type:str]
    GITEA_CLIENT_SECRET: ENC[AES256_GCM,data:D0TlVPKQ9gf4pA==,iv:4mFCaZCrF8L61M2E7PP/NfhuOzVeeBpOtXRIxnXoF6s=,tag:4BFABnqLyWtgQr9nQhABlQ==,type:str]
    ARGOCD_SSO_CLIENT_SECRET: ENC[AES256_GCM,data:P0+ZCmiH3X5x48HB4pvIFhK8STe/JDeaVGvt9YfkNmhQG66avA/eE+kVr0tu48bzXKbwz4FNIxWRNS6/6K4iww==,iv:uTpcrRs0auRzqYW7jG1iq/0YAV66f07NLDAlPS+Xa+M=,tag:YKYqXNX7J/0HI+bcVMiB3Q==,type:str]
    ARGO_WORKFLOWS_SSO_CLIENT_SECRET: ENC[AES256_GCM,data:85Brg089tfGFqod15ySKljfo2H1MPrlidjnnIyuylWH7FwIi045h7nQDKNhRlkjqpz/BZ6tNX8q3w76U7JyKcQ==,iv:Pn+mIxGlY5LJDAF7E7jNwE2quTcs5lia/b3qvYDGebc=,tag:UIDInq2o/tgHvm6yGYaUJA==,type:str]
    DEX_ADMIN_PASSWORD_HASH: ENC[AES256_GCM,data:jby+OZhqhW3lZr9MeXZBT7m7F2nG7/xrxKoqjZwivu6iUcmstE7tPZOJ+hC2q9VLCR670tHcld1fS4Km,iv:MwkboBT2N0iS8m6UwWPyHQXBGNCIjGANkn6WThSeqVk=,tag:Nkn1uSnbBp+PVj+fXWz+SA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eEZxV0k3NnVEeXVrSklS
            ZEUwblNUMldWK2trS2R4czJGVjB4L2J0MG1FClhnWEtVOWdBNGN2akpzOHpaUmlG
            Um1FNGVFNnlpWUtkQ2lLQmxPR3cycHcKLS0tICt2SVdYVy95RFA4cUVWUjYzZWpw
            a0l1UmsrMlJzcjduTTM4TGVDU1RqajQKKq6E12jSjuFANVlWJgiXgGGvJOonHT45
            5gLDCMd1d5GmN8Ur9/K8vw91TdBF9yNZNUTgU5HjxAAn63MAknOxnQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age134a89q3pd6puefa83qu93t4l9dvh08ypq0p4svnfe48jrqu7ppmslc4rrm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-02T00:54:55Z"
    mac: ENC[AES256_GCM,data:f56sp2XHrVJFxBdo0I2c7CxCp3M984NPXudYGnyoIza9fQT5uuT7X3YLn/de5sihQFonFzBmqVSveMuPcSBfzmwgvTXUqyY/3asPn8m6jNyEAlDCGYqzMWy8qYslhkkY2UVwM6yLwB5MVhdFPQJpfaskmBHkwkPqIpvg9x/eoKY=,iv:fhCn59FU/OH/ujyd9DC6rcVIKnj7qW4/7rrW641Q32w=,tag:6xmko3jNMWzAZ3+xADiaCQ==,type:str]
    version: 3.11.0
