apiVersion: v1
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:LazRMou85WxjQRGn5pXLmBJdVe/PXUEvK9fxlWRjB1E0c1kWJpk36ltiM8zeSp9NXqTt3typBRm3EPV3TfxMrg==,iv:T2HCGFGQPB6gu+zEALXcyz92ccOWqBCS9Je4pvuJ7j4=,tag:KyrVuBAT0J59pX3gb9XVAQ==,type:str]
    ADMIN_USERNAME: ENC[AES256_GCM,data:JGwLbA==,iv:zLOA3FSOodC1cWbMvxJHmXVFlEjhb9JqV4SFXI62xbc=,tag:n82nW7LefMa74a+mnq6jqg==,type:str]
    ALERT_PROVIDER: ENC[AES256_GCM,data:27SC4g==,iv:C0PHQQbWg8FfGhuagNIHCsGBhRKbGyTwB8BJcUGkxmo=,tag:dOOvSAYRhOVYrcAY4SBR+A==,type:str]
    NTFY_TOPIC: ENC[AES256_GCM,data:jmosKQ/BvCZIAyydAQ6h/OI6NiM4YWRjFRhxYJiDOo46hHY+lRWPyCGGLgI=,iv:/CEUmRwZGbN7GPHjBW1HH9xr5+i/iRYFVakwVvkXPQE=,tag:w+9J7Piw+GZaqce5/33ycw==,type:str]
kind: Secret
metadata:
    name: disney-alerts-secrets
    namespace: disney-alerts
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdmdoRE1VMkZicDFKejJJ
            SWw0emdBSjhtY1d1TWZNbzZCblRXOFZ6Z3pZCkVqMFErZklWMnF3NCtpdk90bWhq
            eVlmc1cvS3BPNUtoSWhMRVAyeU1Qd2MKLS0tIHRVTkxtWlQ5Nkl5VFZZTjI1RWll
            cUZmR1VDOWtsUlNLSmtMRDdRd2Y3NTQKI8ovP4AjCxlu5b0KPHcuIOQwMp9D76wt
            NxKV73fHPBNs26QDmsRmBCTz9PSzh++Q5+YItKDqaux0y13cXA7kIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age134a89q3pd6puefa83qu93t4l9dvh08ypq0p4svnfe48jrqu7ppmslc4rrm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T12:19:44Z"
    mac: ENC[AES256_GCM,data:LN73Or7aDXeJ6LWmO1bVsee7ZaTEqFVaZMUv+ciW8bXVKlif3dK/dxZcKXg6XElnrU0L9D7zBlRyxcNTfhXQbRkCmiJWwqAD9XxePjv7wbM/K4eil73oNpwQUz2rW8Gn+4OcffjZUYkBJUM4IO/rXr3JP8V+73cJK9DGZxSkhCk=,iv:tIs8kq25ibeQKfmLZ62s1Z2bt+iFxa/U7oEC0Sa5hGA=,tag:cETNpczGwQ14ZTy5Dsgu+g==,type:str]
    version: 3.13.3
