apiVersion: v1
kind: Secret
metadata:
    name: kitchenowl-secret
    namespace: kitchenowl
type: Opaque
stringData:
    JWT_SECRET_KEY: ENC[AES256_GCM,data:1G96SsiPwcoQL8mqziG4B4AlXdtMEClef/yJSrI7H6stmhtMFbwZb63rSoV13Fg+pFWh9Q4CB9PsKpNwvzraeIisy5JLxPRF3tq2quLnueRREYsEF+rkWoAKSNfxJIhY,iv:ZaIe3+NzrRh0pEfkhTP7kG1/9zDWulJrgOle+Zl0Xgw=,tag:09pt3/WDgcUxRmcEZfyufg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdUMzRklJU0lqaWIvbTlW
            OHBtTTB2SlVQZFNQLzB1bk1PME91Sms2czJBClVpanppNHNWa3RobGVyM09kc3BZ
            N1A5d0JxZlpaRnRZZTczUjcybnZ1ZzQKLS0tIEJiUkUwbU1RRER6Vm83L214bTMv
            ZUJGN1FjbzdWKzhDQnhqWTVjTVVodEEKiokdYV2RixGZfaWgMLCqBS6iQ+dGpRyQ
            rS+zMm4OXUKGIsxZR38yzvbkY7LN5bOB6bynC3l+qsEV13j1RBVJ/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age134a89q3pd6puefa83qu93t4l9dvh08ypq0p4svnfe48jrqu7ppmslc4rrm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-02T00:54:55Z"
    mac: ENC[AES256_GCM,data:kTdKLeOIlEDpXXmMVPGu7rMtwgAigkGCy6bnoeldkgkt4bQqiB/8wxUVDig94Aq4eKsE6Bddv5KSf9UVM5TykHg78fXMLNaoXQnVKE3P3YSy2vIDYmBH4FxYvljOGpJvMEzwSQhe9KUMyb5QwN/rAw5KMNLmHW4DlWFL4vC6zmk=,iv:GpT7BJ7JmZjZ9l1QNv1z+BzQD07xoLbj1q09ZnLZ3kY=,tag:Pp94MmY4FvuOeb3BHVNtOg==,type:str]
    version: 3.13.3
