apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
    namespace: paperless
type: Opaque
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:szqiQa+imJR7KnBrtHsRIFBmFAM8QERYlSUslXMThB+1Q3oKsMTrWBEe8gNoJKdPSwdLEiB0MD54tv4/FQVsmQ==,iv:m25+8V+NhKnDyz2IQZoapdo2ltCdrdKr4rNMvbdwPlM=,tag:0H8IwyZrpGGoN0y6mnnDeA==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:ypJEef4=,iv:X0pD3VLJn/1Cl0cAj4G2Dj6YdiKr0FTtAN9tCU8BIHY=,tag:2E8x4ufC4c6zj2vgH8TS8w==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:HtXBxi8ZKeYCPcB5th1/ZGCUTGX/ZzSHSK6Qpdx1w0PuOCykRU1y7iU/Sjr2Rp2Z,iv:8zE6fRLg/FQ5DI3w51kdJMvEMEVvH1P/xyQPIHhVQQo=,tag:s/x6qKf1zy+cBFX+tFnZdQ==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:dRx1fzIT9F5R47h2uum55X4H9X4eFEu6AlG3GV/h6nQ8cw72lKUzzC4e/OEygQr+/ozaEpR5FoX6oSME84m0tiDlpSHHoOe4HD7NE8v9nojnEKDhy/OOagdHyr27AJlBobAPGRpya1BcidPyUqOBML/rsycqbIeyYBD4mL4MyNY8/TqvjcPmN2UljHbr87VYKRih0BUonx67Coq7xrtqe9GN0Yiu92cGxHnhLZt7A05+6r9O7cfGZ1JvLyxPKMy9qnnibCekF/fJGY+NkHWMKmcH9MLm0/uXZ5E3PpHwKN3JB8df4b9agpcSjreNkheBdoJw8dbGLrcSg4lf4vQ8lqfE5mS4QrFHvCDdPJGB0Lt4LN+wcM11SiWPm+NqjsvyRFhkjNMHQVS/FA==,iv:4V3n2WRGxaNolvnBfwykW9kT5lDc5fBJe9UyGKvDkI0=,tag:2D8ZnfTI3wFWm0HOFYOgjA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSnVrYnQ1SFhZS1liaXJv
            NytkRDBidFhKcUkxSzN0aWh6a05FT05mN1VRCmpwcjIwZHlBemlsdlRxeUcrVmxL
            cVFJVll3NU9pUUVCSTJ1RXUyVjBRMnMKLS0tIGlKTGFrZVZOZkNKcjh1NllscEw2
            NVpBL2xyc0JwdmhMOXU1OXNyZGVFNHcKa8b0by0o1yQZR5g0V0/iVkzxIKd9XhBf
            +j5X/yhSArJkH1n4mx7/6AR3f6nGC/0tLEAxTXuT3+621lkSjdXWdg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age134a89q3pd6puefa83qu93t4l9dvh08ypq0p4svnfe48jrqu7ppmslc4rrm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T15:01:52Z"
    mac: ENC[AES256_GCM,data:Zpx6o5/4GkwrtSgTRTuWzOLxa/j3SVW02WOOz0mK3nW8Yn5m+zfQRnyBKK12mWd6b0tBYk5pL9oOYCaoCeuH50R5gP6IZXyuHjuDWKLJzlrBtRMQorck/DIxo2TFPAm4poIFxgYoadQ2qglvt0tWeDWqDw4O94zIPsYDVwyAhqE=,iv:vdBkn2Ogb+j2u1v5vORHds+r5vLhYH7wOH73iJbNqFI=,tag:l9V46tVSDbhOHgyjiZ5GBQ==,type:str]
    version: 3.13.3
