apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secrets
    namespace: recyclarr
type: Opaque
stringData:
    SONARR_API_KEY: ENC[AES256_GCM,data:WcQfeutopch8ZISjqz9yWeVnDZGzloVSrlhZWeVBSDI=,iv:l30ZhQIodW0eAPIuiXNmatzueMEF8il8iUNWHHNqP8s=,tag:iL65D/WAtAqRcabDk+IrBA==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:9fr0q3QtkZTDWqcwR2LLBcYg9S3DkfIoBtp5I2uOWj4=,iv:Pgn3SVrGwIhEh3SxldVQ6GDhfB7KNgJ/FEcHD+B4kRs=,tag:7Z/XjrMqq7TmdQSb05/h5A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTnQ1VC83ZURUeEx6Slk5
            dFJURDQyWXo1R2V6Rk81ZzlvcDJzTFpnbVRJCnlHcDE0MEIzZkdBSkZMYkExQkVy
            a3MyVjRNMWRxaFNWeVI1Ums3V0YxRTQKLS0tIDhzU2IrRWxYRjF4SUcrNFBPZlFW
            Skk3MlRQNytqbzVjMFFMN2lQMW5wNjAKvIaXh4YdD6Vxo9Db55iSw3kRMd+oyc0O
            MV1B4bitgzJ9+M6pN23yqTLi+os0kGUTwa2/xtc1AA51yWbkrA7YHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age134a89q3pd6puefa83qu93t4l9dvh08ypq0p4svnfe48jrqu7ppmslc4rrm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T12:15:22Z"
    mac: ENC[AES256_GCM,data:K78qgOptmijGdluxgeqLAIJG6ylSX8zUqtjc+uwSLGuZDPDgbWB7QUIXtqf4vYqLyKodN8tsFDdD4GPiLU+CKqcfqJsjUO3HqG2QxZQ/PrsxmaBQxYFNNM16kDkViIEtKkOR9DfpQpDOzurCXXcKx/a8zdAHpbn8kVg+5qZll2o=,iv:e7AdXXThANpirTO4XmFJY7vvLwtFCGrqYa1wPrAo4P8=,tag:45vN4zf4iML63okWkDZSrA==,type:str]
    version: 3.13.3
