apiVersion: v1
kind: Secret
metadata:
    name: restic-rest-server-auth
    namespace: restic-rest-server
type: Opaque
stringData:
    .htpasswd: ENC[AES256_GCM,data:AFF7dVoZc2p5ffVf+Agmg1agpEx4a0BxpZIVuBqq+Oh+IMnUL8DnpQAHvqe2Sv9R6R6cx3fgv1n2TrIGCjYswCoPP7Gp,iv:dzlBsgp9WM0JzhG+q8ZJu/8MRjotkTCzw5osN4S5RGs=,tag:UF1SKJREihV3PkdthRtFVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQjFGK0w5ODZiRjd4dWtW
            Y00xZ0JNSnV1UndNTWVocWVuUS9UaldrclVnCnIxY1FVOWI4QVpyWFQrN2VMZjYz
            TGowNzhlV0dIMTdQbWJZQnB4dHljT28KLS0tIHhVc0g4bEU1L2tNbHh0LzlKRVF2
            Tzdadkt0ZENHU0tROEJYMkhrM1VvMm8K2k6/lXUEyFY2cKVlYWxKM61EH0ZNYbp1
            wzwWcehQHuvXGbOmm5EdaCnk7llScLQYs4rEprpPPM/HV4QAKx/ZLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age134a89q3pd6puefa83qu93t4l9dvh08ypq0p4svnfe48jrqu7ppmslc4rrm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T00:25:58Z"
    mac: ENC[AES256_GCM,data:SbsAXnsriQAK86lyqhFSyS58ANNMXSGmb755Sj7FkhaecQK+sY24Ov2VYQWUYIVx5JjW4gwrKG9DLYxTazD4urw39UMb9eSccDfTLj/jW0aRIj69ThCadbwnukX+iNRUEQHW08W/Aa1MowsU7fgKmA+OZBfzB3vOoCCwmILUyjQ=,iv:wiJCqgPC02C1TTEcn0b3oqDU2c4Po3j3jGDczUfUwfo=,tag:/m4UR0kUnfEbSOw3ygov3g==,type:str]
    version: 3.13.3
