apiVersion: v1
data:
    DB_PASSWD: ENC[AES256_GCM,data:wabgojdVolLjWxm5UZGPXg==,iv:Af9hEbyPa4ZCMoR+sIv2tv6UUOXajjNXsQ9cFLVWB+4=,tag:72LD2YDRijyWzQrahaATGQ==,type:str]
    MARIADB_PASSWORD: ENC[AES256_GCM,data:Z1TmYd5Ox8uf+eccXNk+lw==,iv:dmQ87PtrA4kHvVqQkhz4nqGMBULwTOQH0qBiRysmhUw=,tag:fuXiLsUdQwb+W076CETfsw==,type:str]
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:Wl4C1pDHSW/b0Q+dP7F7DyoNtZc=,iv:Irivqcbb2c/Q5++vJeeFDjB+cx17e++ko8TpH+BFMZc=,tag:/Dfz1NHl/6GGbbvMOXETSQ==,type:str]
    ROMM_AUTH_SECRET_KEY: ENC[AES256_GCM,data:XF+WmKEmN5aXeOJchnFHt56icLnDvsRIRMah11LWa1q57z0jqRCAhm7Eois0mpWfFbnfr4q3Tc95B4TdyW44ajn/uvs/SxrjoMfHS+WYvvW1cb6y+wb0gw==,iv:s82J44I1QfIrz3aooVi1+Ks3gWjEDDZM7/qVN4lx8CE=,tag:AZjrPTYgrmJqRvDyxj9t3g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: romm-secrets
    namespace: romm
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdWZaNDFOck00ZHBGK3Ez
            RVUwT0QydWc0UUJLTjNoWFBJR0E1TWMwb0ZFCkZmQXpSTWszQ0tRT0t2YTNRaDBS
            UGx5cm9rdWJaQXppSnR5alhpYjNWQjQKLS0tIGRHdjhLSk40bjNIYTl5T1VubDQ2
            VjlxU1NoQkduZ0FCRlVvR25VZUlrNVEKFBo8lZeXYUwxP54HU/nCuvrYmXUWnlYo
            9m4BscDF2RXgP8R5YXCVlBGamevZtpoEtMWs3BOO6FdFWwmM41eZtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age134a89q3pd6puefa83qu93t4l9dvh08ypq0p4svnfe48jrqu7ppmslc4rrm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T01:08:22Z"
    mac: ENC[AES256_GCM,data:cqnazqCtVI95Z6nrlmKysNzfbJIuxEPbWI8OcjCOouShe7ZnQOZyHnt6ojrQfcx1HQlWoMQajdAh9eQB90dq0RMYnSaWOPg1En3A91Xi5fpInCuX8AiGjdYQySmOJg5xHiqddEAlZwQRNcyJzE+diCZ5byYTsz+ccXFXctKaVOM=,iv:7TScRDmvJb7GtkUKNKWgTFIW3EBVHNMfskVq7ZFF4+4=,tag:+tTS9TAk02rPFyFV60cxBA==,type:str]
    version: 3.13.3
