apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: freshlab-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - argocd-notifications-secret.sops.yaml
  - argocd-oidc.sops.yaml
  - argo-workflows-sso.sops.yaml
  - authelia-config.sops.yaml
  - cert-manager-cloudflare-api-token.sops.yaml
  - dex-secrets.sops.yaml
  - disney-alerts-app.sops.yaml
  - external-dns-cloudflare-api-token-secret.sops.yaml
  - frigate-rstp-credentials.sops.yaml
  - grafana-secrets.sops.yaml
  - immich-db.sops.yaml
  - kindle.sops.yaml
  - kitchenowl-secret.sops.yaml
  - kube-prometheus-stack-grafana-admin.sops.yaml
  - runners-gh-arc-app.sops.yaml
  - tailscale-auth.sops.yaml
