apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: freshlab-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - argocd-notifications-secret.sops.yaml
  - argocd-oidc.sops.yaml
  - argo-workflows-sso.sops.yaml
  - authelia-config.sops.yaml
  - cert-manager-cloudflare-api-token.sops.yaml
  - dex-secrets.sops.yaml
  - disney-browser-state.sops.yaml
  - disney-alerts-app.sops.yaml
  - disney-alerts-sso.sops.yaml
  - external-dns-cloudflare-api-token-secret.sops.yaml
  - frigate-rstp-credentials.sops.yaml
  - hermes-env.sops.yaml
  - grafana-secrets.sops.yaml
  - immich-db.sops.yaml
  - kindle.sops.yaml
  - kitchenowl-secret.sops.yaml
  - kube-prometheus-stack-grafana-admin.sops.yaml
  - kube-prometheus-stack-alertmanager-smtp.sops.yaml
  - runners-gh-arc-app.sops.yaml
  - volsync-restic/authelia-data-volsync-restic.sops.yaml
  - volsync-restic/autobrr-config-volsync-restic.sops.yaml
  - volsync-restic/disney-alerts-data-volsync-restic.sops.yaml
  - volsync-restic/freshrss-pvc-volsync-restic.sops.yaml
  - volsync-restic/frigate-config-volsync-restic.sops.yaml
  - volsync-restic/frigate-media-volsync-restic.sops.yaml
  - volsync-restic/grocy-data-volsync-restic.sops.yaml
  - volsync-restic/immich-postgres-data-volsync-restic.sops.yaml
  - volsync-restic/kitchenowl-data-volsync-restic.sops.yaml
  - volsync-restic/mealie-data-volsync-restic.sops.yaml
  - volsync-restic/mysql-data-pvc-volsync-restic.sops.yaml
  - volsync-restic/paperless-data-volsync-restic.sops.yaml
  - volsync-restic/pms-config-plex-0-volsync-restic.sops.yaml
  - volsync-restic/prowlarr-config-volsync-restic.sops.yaml
  - volsync-restic/qbittorrent-config-volsync-restic.sops.yaml
  - volsync-restic/romm-redis-data-pvc-volsync-restic.sops.yaml
  - volsync-restic/romm-resources-pvc-volsync-restic.sops.yaml
  - volsync-restic/seerr-config-volsync-restic.sops.yaml
  - volsync-restic/sonarr-config-volsync-restic.sops.yaml
  - volsync-restic/tautulli-config-volsync-restic.sops.yaml
  - volsync-restic-media/hermes-data-volsync-restic.sops.yaml
  - volsync-restic-media/radarr-config-volsync-restic.sops.yaml
  - restic-rest-server-auth.sops.yaml
  - romm-secrets.sops.yaml
  - paperless.sops.yaml
  - mealie-oidc.sops.yaml
  - media-stack-oidc.sops.yaml
  - recyclarr-secrets.sops.yaml
