protectedNamespaces:
  - policy
  - argo-rollouts
  - arc
  - arc-system2
  - arc-runners

networkPolicyNamespaces:
  - autobrr
  - budget
  - disney-alerts
  - excalidraw
  - flask
  - freshrss
  - frigate
  - grocy
  - hajimari
  - hermes
  - immich
  - kindle-weather
  - kitchenowl
  - kube-ops-view
  - librespeed
  - mealie
  - nginx
  - paperless
  - plex
  - prowlarr
  - qbittorrent
  - radarr
  - recyclarr
  - romm
  - restic-rest-server
  - seerr
  - sonarr
  - tautulli
  - tools
  - uptime-kuma
