apiVersion: v1
kind: Service
metadata:
  name: romm
spec:
  selector:
    app: romm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: romm-db
spec:
  selector:
    app: romm-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
