grafana:
  freshlabAppDashboards:
    - budget
    - disney-alerts
    - excalidraw
    - flask
    - freshrss
    - frigate
    - grocy
    - hajimari
    - immich
    - kindle-weather
    - kitchenowl
    - kube-ops-view
    - librespeed
    - mealie
    - mqtt
    - nginx
    - plex
    - romm
    - seafile
    - tools
    - uptime-kuma
  ingress:
    enabled: true
    ingressClassName: istio
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - &host grafana.kleinsorge.dev
    tls:
      - secretName: grafana-general-tls
        hosts:
          - *host
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
      label: grafana_dashboard
      labelValue: "1"
    datasources:
      enabled: true
      searchNamespace: grafana
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          uid: prometheus
          type: prometheus
          access: proxy
          url: http://kube-prometheus-stack-prometheus.kube-prometheus-stack:9090
          isDefault: true
          jsonData:
            httpMethod: POST
            timeInterval: 30s
        - name: node
          uid: node
          type: prometheus
          access: proxy
          url: http://kube-prometheus-stack-prometheus.kube-prometheus-stack:9090
        - name: Loki
          uid: Loki
          type: loki
          access: proxy
          url: http://loki.loki:3100
        - name: Tempo
          uid: Tempo
          type: tempo
          access: proxy
          url: http://tempo.tempo:3200
  additionalDataSources:
    - name: Prometheus
      uid: prometheus
      type: prometheus
      access: proxy
      url: http://kube-prometheus-stack-prometheus.kube-prometheus-stack:9090
      isDefault: true
      jsonData:
        httpMethod: POST
        timeInterval: 30s
    - name: Loki
      uid: Loki
      type: loki
      access: proxy
      url: http://loki.loki:3100
    - name: Tempo
      uid: Tempo
      type: tempo
      url: http://tempo.tempo:3200
      access: proxy
      basicAuth: false
      jsonData:
        httpMethod: GET
        serviceMap:
          datasourceUid: prometheus
        tracesToLogsV2:
          datasourceUid: Loki
          filterByTraceID: true
          filterBySpanID: false
        tracesToMetrics:
          datasourceUid: prometheus
  envFromSecret: grafana-secrets
  grafana.ini:
    server:
      root_url: https://grafana.kleinsorge.dev
    auth.generic_oauth:
      enabled: true
      allow_sign_up: true
      name: Dex
      client_id: grafana-sso
      client_secret: $__env{GRAFANA_SSO_CLIENT_SECRET}
      scopes: openid profile email groups
      auth_url: https://dex.kleinsorge.dev/auth
      token_url: https://dex.kleinsorge.dev/token
      api_url: https://dex.kleinsorge.dev/userinfo
