- name: Ensure MetalLB namespace exist
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: 'metallb-system'
    state: present

- name: Add labels to MetalLB namespace
  kubernetes.core.k8s:
    state: patched
    kind: Namespace
    name: 'metallb-system'
    definition:
      metadata:
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/warn: privileged

- name: Create MetalLB configmap
  kubernetes.core.k8s:
    definition: "{{ lookup('file', 'configmap.yaml') | from_yaml }}"

# - name: Create MetalLB ip pool
#   shell: |
#     cat <<EOF | kubectl apply -n metallb-system -f - 
#     apiVersion: metallb.io/v1beta1
#     kind: IPAddressPool
#     metadata:
#       name: production
#       namespace: metallb-system
#     spec:
#       addresses:
#         - 192.168.2.100-192.168.2.200
#     EOF