tdarr:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        tdarr.io/enable: 'true'
        hajimari.io/appName: tdarr
        hajimari.io/icon: swap-horizontal
      hosts:
        - host: &host tdarr.kleinsorge.us
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: tdarr-tls-certificate
          hosts:
            - *host
  persistence:
    media:
      enabled: true
      type: nfs
      server: 192.168.1.208
      path: /volume1/Media/Movies
  node:
    enabled: true
