firefly-db:
  storage:
    accessModes: ReadWriteOnce
    dataSize: 1Gi
  backup:
    destination: http
    pvc:
      accessModes: ReadWriteOnce
      dataSize: 1Gi
  configs:
    DBHOST: firefly-firefly-db
    DBPORT: "5432"
    DBNAME: firefly
    DBUSER: firefly
    TZ: New_York/America
    POSTGRES_HOST_AUTH_METHOD: trust
    POSTGRES_USER: firefly
    POSTGRES_PASSWORD: "CHANGE_ENCRYPT_ME"
