apiVersion: v1
kind: Service
metadata:
  name: disney-alerts
  labels:
    app: disney-alerts
spec:
  selector:
    app: disney-alerts
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
