apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: replica-auto-balance-disk-pressure-percentage
  namespace: {{ .Release.Namespace }}
value: {{ .Values.longhorn.defaultSettings.replicaAutoBalanceDiskPressurePercentage | quote }}
