uptime-kuma:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        uptime-kuma.io/enable: 'true'
        hajimari.io/appName: uptime-kuma
        hajimari.io/icon: arrow-up-bold-box
      hosts:
        - host: &host status.kleinsorge.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: uptime-kuma-tls-certificate
          hosts:
            - *host
  persistence:
    data:
      enabled: true
      type: nfs
      server: 192.168.1.208
      path: /volume1/kube/uptime-kuma
      # mountPath: /app/data