apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex            
  labels: plex
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/app-root: /web             
spec:
  ingressClassName: nginx
  rules:
    - host: &host plex.kleinsorge.dev
      http:
        paths:
          - path: /     
            pathType: Prefix 
            backend:
              service:
                name: plex
                port:
                  number: 32400
  tls:
    - secretName: plex-tls-certificate
      hosts:
        - *host

