apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-data-pvc
spec:
  storageClassName: ""
  volumeName: plex-data-pv
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Ti
