kind: Service
apiVersion: v1
metadata:
  name: plex
  labels: plex
spec:
  selector:
    app: plex
  ports:
    - port: 32400
      targetPort: 32400
      name: plex-port 
      protocol: TCP
      nodePort:
  type: ClusterIP
