apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kindle-weather
  labels:
    app: kindle-weather
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: kindle-weather
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s

