---
apiVersion: v1
kind: Service
metadata:
  name: kindle-weather-service
  labels:
    app: kindle-weather
spec:
  selector:
    app: kindle-weather
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
