apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: immich-rwo
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  dataLocality: disabled
  fromBackup: ""
  fsType: ext4
  dataEngine: v1
  unmapMarkSnapChainRemoved: ignored
  backupTargetName: default
  disableRevisionCounter: "true"
