apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library-pv
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.208
    path: /volume1/photo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
spec:
  storageClassName: ""
  volumeName: immich-library-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgres-data
spec:
  storageClassName: immich-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
