apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflows-sso-admin
  namespace: {{ .Release.Namespace }}
  annotations:
    workflows.argoproj.io/rbac-rule: "'freshlab-admins' in groups"
    workflows.argoproj.io/rbac-rule-precedence: "10"
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-workflows-sso-admin.service-account-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: argo-workflows-sso-admin
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflows-sso-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-argo-workflows-admin
subjects:
  - kind: ServiceAccount
    name: argo-workflows-sso-admin
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflows-sso-readonly
  namespace: {{ .Release.Namespace }}
  annotations:
    workflows.argoproj.io/rbac-rule: "true"
    workflows.argoproj.io/rbac-rule-precedence: "0"
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-workflows-sso-readonly.service-account-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: argo-workflows-sso-readonly
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflows-sso-readonly
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-argo-workflows-view
subjects:
  - kind: ServiceAccount
    name: argo-workflows-sso-readonly
    namespace: {{ .Release.Namespace }}
