apiVersion: v1
kind: PersistentVolume
metadata:
  name: authelia-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.208
    path: /volume1/kube/authelia
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-data
spec:
  storageClassName: ""
  volumeName: authelia-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
