app-template:
  domain: toolstowelsandfroods.com
  controller:
    annotations:
      reloader.stakater.com/auto: "true"
    type: statefulset
  image:
    repository: ghcr.io/authelia/authelia
    tag: master@sha256:7ce56abf45e6752e966d99d4d6c83d4737737eba45724118fb1f8e79f1f428df
  args: ["--config", "/etc/authelia/config.yaml"]
  service:
    main:
      ports:
        http:
          port: &port 80
        metrics:
          enabled: true
          port: 8080
  ingress:
    main:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: "true"
        hajimari.io/icon: lock
        hajimari.io/appName: Authelia
        hajimari.io/info: Authentication and authorization, MFA and SSO
      hosts:
        - host: &host auth.kleinsorge.dev
          paths:
            - path: /

      tls:
        - secretName: authelia-tls-certificate
          hosts:
            - *host
  env:
  - name: TZ
    value: America/New_York
  envFrom:
    - secretRef:
        name: authelia-secrets
  enableServiceLinks: false
  resources:
    requests:
      cpu: "0.25"
      memory: 50Mi
    limits:
      cpu: "4.00"
      memory: 120Mi
  rbac:
    enabled: true
 # secret:
 #   existingSecret: authelia-secrets
  persistence:
    config:
      enabled: true
      type: configMap
      name: authelia-config
      subPath: config.yaml
      mountPath: /etc/authelia/config.yaml
      readOnly: false
