---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-kleinsorge-dev
  namespace: default
spec:
  secretName: traefik-kleinsorge-dev-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "traefik.kleinsorge.dev"
  dnsNames:
  - "traefik.kleinsorge.dev"
