frigate:
  strategyType: Recreate
  image:
    repository: ghcr.io/blakeblackshear/frigate
    pullPolicy: IfNotPresent
  env:
    TZ: UTC
  envFromSecrets: []
    # secrets are required before `helm install`
    # - frigate-rstp-credentials
  extraVolumes: []
  extraVolumeMounts: []
  shmSize: 1Gi
  tmpfs:
    enabled: true
    sizeLimit: 1Gi
  config: |
    mqtt:
      # Required: host name
      host: mqtt.server.com
      # Optional: port (default: shown below)
      port: 1883
      # Optional: topic prefix (default: shown below)
      # WARNING: must be unique if you are running multiple instances
      topic_prefix: frigate
      # Optional: client id (default: shown below)
      # WARNING: must be unique if you are running multiple instances
      client_id: frigate
      # Optional: user
      user: mqtt_user
      # Optional: password
      # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
      #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
      password: password
      # Optional: interval in seconds for publishing stats (default: shown below)
      stats_interval: 60

    detectors:
      # coral:
      #   type: edgetpu
      #   device: usb
      cpu1:
        type: cpu

    cameras:
      # Name of your camera
      front_door:
        ffmpeg:
          inputs:
            - path: rtsp://{FRIGATE_RSTP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@10.0.10.10:554/cam/realmonitor?channel=1&subtype=2
              roles:
                - detect
                - rtmp
        width: 1280
        height: 720
        fps: 5
  # Probes configuration
  probes:
    liveness:
      enabled: true
      initialDelaySeconds: 30
      failureThreshold: 5
      timeoutSeconds: 10
    readiness:
      enabled: true
      initialDelaySeconds: 30
      failureThreshold: 5
      timeoutSeconds: 10
    startup:
      enabled: false
      failureThreshold: 30
      periodSeconds: 10

  service:
    # -- Type of Service to use
    type: ClusterIP
    # -- Port the Service should communicate on
    port: 5000
    ## Specify the nodePort value for the LoadBalancer and NodePort service types.
    ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
    ##
    # nodePort:
    ## Provide any additional annotations which may be required. This can be used to
    ## set the LoadBalancer service type to internal only.
    ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
    ##
    annotations: {}
    labels: {}

    # -- Set specific IP address for LoadBalancer. `service.type` must be set to `LoadBalancer`
    loadBalancerIP:

    # loadBalancerSourceRanges: []
    ## Set the externalTrafficPolicy in the Service to either Cluster or Local
    # externalTrafficPolicy: Cluster

    # default IP family to use for the service
    ipFamilyPolicy: SingleStack
    # ipFamilies for service
    ipFamilies: []

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: frigate 
      hajimari.io/icon: video-camera
    hosts:
      - host: &host frigate.kleinsorge.dev
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: frigate-tls-certificate
        hosts:
          - *host

  persistence:
    config:
      # -- Enables persistence for the config directory
      enabled: false
      ## frigate data Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      # storageClass: "-"
      ##
      ## If you want to reuse an existing claim, you can pass the name of the PVC using
      ## the existingClaim variable
      # existingClaim: your-claim
      # subPath: some-subpath

      # -- [access mode](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes) to use for the PVC
      accessMode: ReadWriteOnce

      # -- size/capacity of the PVC
      size: 100Mi

      # -- Do not delete the pvc upon helm uninstall
      skipuninstall: false

    media:
      # -- Enables persistence for the media directory
      enabled: false
      ## frigate data Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      # storageClass: "-"
      ##
      ## If you want to reuse an existing claim, you can pass the name of the PVC using
      ## the existingClaim variable
      # existingClaim: your-claim
      # subPath: some-subpath

      # -- [access mode](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes) to use for the PVC
      accessMode: ReadWriteOnce

      # -- size/capacity of the PVC
      size: 10Gi

      # -- Do not delete the pvc upon helm uninstall
      skipuninstall: false

   # -- Node Selector configuration
  nodeSelector: {}

  # -- Node toleration configuration
  tolerations: []

  # -- Set Pod affinity rules
  affinity: {}

