apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: 'https://charts.min.io/'
    targetRevision: 4.0.15
    helm:
      values: |-
        environment:
          MINIO_BROWSER_REDIRECT_URL: https://minio-console.kleinsorge.dev
        ingress:
          enabled: true
          path: /
          hosts:
            - minio.kleinsorge.dev
          tls:
            - secretName: minio-tls
              hosts:
                - minio.kleinsorge.dev
        consoleIngress:
          enabled: true
          path: /
          hosts:
            - minio-console.kleinsorge.dev
          tls:
            - secretName: minio-console-tls
              hosts:
                - minio-console.kleinsorge.dev
        replicas: 1
        rootUser: minio
        rootPassword: password
        persistence:
          enabled: true
          existingClaim: local-path-pvc
          storageClass: "local-path"
          accessMode: ReadWriteOnce
          size: 512Mi
        resources:
          requests:
            memory: 500Mi
        gateway:
          replicas: 1
        mode: standalone
        buckets:
         - name: vault-backend
          policy: none
          purge: true
          versioning: false
          objectlocking: false
    chart: minio
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
