home-assistant:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        ombi.io/enable: 'true'
        hajimari.io/appName: home-assistant
        hajimari.io/icon: lightbulb-on
      hosts:
        - host: &host home-assistant.kleinsorge.us
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: home-assistant-tls-certificate
          hosts:
            - *host
  persistence:
    config:
      enabled: true
      type: nfs
      server: 192.168.1.208
      path: /volume1/kube/ha
  env:
    PUID: '1030'
    PGID: '101'
  # influxdb:
  #   enabled: true
  #   architecture: standalone
  #   database: home_assistant
  #   authEnabled: false
  #   persistence:
  #     enabled: true
