librespeed:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        librespeed.io/enable: 'true'
        hajimari.io/appName: librespeed
        hajimari.io/icon: speedometer
      hosts:
        - host: &host librespeed.kleinsorge.us
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: librespeed-tls-certificate
          hosts:
            - *host
