yuta:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: yuta
        hajimari.io/icon: google-drive
      hosts:
        - host: &host yuta.kleinsorge.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: yuta-tls-certificate
          hosts:
            - *host
  core:
    enabled: true
  messaging:
    enabled: false
  webhook:
    enabled: true
  nats:
    enabled: true
