apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-config 
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.200-192.168.1.205
# ---
# apiVersion: metallb.io/v1beta1
# kind: L2Advertisement
# metadata:
#   name: l2adv
#   namespace: metallb-system
