apiVersion: apps/v1
kind: Deployment
metadata:
  name: photoprism
  namespace: photoprism
spec:
  selector:
    matchLabels:
      app: photoprism
  replicas: 1
  template:
    metadata:
      labels:
        app: photoprism
    spec:
      containers:
        - name: photoprism
          image: photoprism/photoprism:latest
          env:
            - name: PHOTOPRISM_DEBUG
              value: 'true'
            - name: PHOTOPRISM_CACHE_PATH
              value: /assets/cache
            - name: PHOTOPRISM_IMPORT_PATH
              value: /assets/photos/import
            - name: PHOTOPRISM_EXPORT_PATH
              value: /assets/photos/export
            - name: PHOTOPRISM_ORIGINALS_PATH
              value: /assets/photos/originals
            - name: PHOTOPRISM_DATABASE_DRIVER
              value: mysql
            - name: PHOTOPRISM_DATABASE_NAME
              value: photoprism
            - name: PHOTOPRISM_DATABASE_PASSWORD
              value: CHANGEMEIMAPASSWORD
            - name: PHOTOPRISM_DATABASE_SERVER
              value: photoprism-db-service.photoprism.svc.cluster.local:3306
            - name: PHOTOPRISM_DATABASE_USER
              value: photoprism
            - name: PHOTOPRISM_WORKERS
              value: '6'
            - name: PHOTOPRISM_ORIGINALS_LIMIT
              value: '-1'
            - name: PHOTOPRISM_RESOLUTION_LIMIT
              value: '-1'
            - name: PHOTOPRISM_ADMIN_PASSWORD
              value: 'please-change'
          ports:
            - containerPort: 2342
              name: http
          volumeMounts:
            - mountPath: /assets/photos/originals
              name: photoprism-originals-pvc
              subPath: media/photos
            - mountPath: /assets/photos/import
              name: photoprism-import-pvc
              subPath: import
            - mountPath: /photoprism/storage
              name: photoprism-config-pvc
          readinessProbe:
            httpGet:
              path: /api/v1/status
              port: http
      volumes:
        - name: photoprism-originals-pvc
          persistentVolumeClaim:
            claimName: photoprism-originals-pvc
        - name: photoprism-config-pvc
          persistentVolumeClaim:
            claimName: photoprism-config-pvc
        - name: photoprism-import-pvc
          persistentVolumeClaim:
            claimName: photoprism-import-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: photoprism-service
  namespace: photoprism
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: photoprism
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        photoprism.io/enable: 'true'
        hajimari.io/appName: photos
        hajimari.io/icon: camera
        nginx.ingress.kubernetes.io/proxy-body-size: "512M"
spec:
  ingressClassName: nginx
  rules:
   - hosts:
        - host: &host photos.kleinsorge.dev
          paths:
            - path: /
              pathType: Prefix
  tls:
    - secretName: photoprism-tls-certificate
      hosts:
        - *host
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-config-pvc
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100G
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: photoprism
  name: photoprism-originals-pvc
spec:
  accessModes:
    - ReadOnlyMany
  volumeName: photoprism-originals-pv
  resources:
    requests:
      storage: 10Ti
  storageClassName: ''
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: photoprism
  name: photoprism-import-pvc
spec:
  accessModes:
    - ReadOnlyMany
  volumeName: photoprism-import-pv
  resources:
    requests:
      storage: 100Gi
  storageClassName: ''
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: photoprism-originals-pv
spec:
  capacity:
    storage: 10Ti
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 192.168.1.208
    path: /volume1/Media/Memories
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: photoprism-import-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 192.168.1.208
    path: /volume1/Photos