photoprism:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        photoprism.io/enable: 'true'
        hajimari.io/appName: photo
        hajimari.io/icon: film
        nginx.ingress.kubernetes.io/proxy-body-size: "512M"
      hosts:
        - host: &host photo.kleinsorge.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: photoprism-tls-certificate
          hosts:
            - *host
  mariadb:
    enabled: true
    auth:
      database: photoprism
      username: photoprism
      password: photoprism
      rootPassword: photoprism
  persistence:
    config:
      enabled: true
      type: nfs
      server: 192.168.1.208
      path: /volume1/kube/photoprism
    originals:
      enabled: true
      type: nfs
      server: 192.168.1.208
      path: /volume1/Media/Memories
    import:
      enabled: true
      type: nfs
      server: 192.168.1.208
      path: /volume1/photo
  