replicaCount: 2
server:
  debug: "true"
  persistence:
    enabled: true
    cachePath: &cachePath /assets/cache
    importPath: &importPath /assets/photos/import
    exportPath: &exportPath /assets/photos/export
    originalsPath: &originalsPath /assets/photos/originals
    volumeMounts:
    - name: originals
      mountPath: *originalsPath
      subPath: "media/photos"
    - name: photoprism
      mountPath: *cachePath
      subPath: "cache"
    - name: photoprism
      mountPath: *importPath
      subPath: "import"
    - name: photoprism
      mountPath: *exportPath
      subPath: "export"
    volumes:
    - name: config
      nfs:
        server: 192.168.1.208
        path: /volume1/kube/photoprism
    - name: originals
      nfs:
        server: 192.168.1.208
        path: /volume1/Media/Memories
        readOnly: true
    - name: import
      nfs:
        server: 192.168.1.208
        path: /volume1/photo

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    photoprism.io/enable: 'true'
    hajimari.io/appName: photo
    hajimari.io/icon: film
    nginx.ingress.kubernetes.io/proxy-body-size: "512M"
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required - private
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
  hosts:
    - host: &host photos.kleinsorge.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: photoprism-tls-certificate
      hosts:
        - *host
