apiVersion: apps/v1
kind: Deployment
metadata:
  name: tools
  labels:
    app: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tools
  template:
    metadata:
      labels:
        app: tools
    spec:
      containers:
      - name: tools
        image: iib0011/omni-tools:latest
        ports:
        - containerPort: 80
        restartPolicy: Always

