apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-pvc
  namespace: freshrss
  labels:
    app.kubernetes.io/instance: freshrss
    app.kubernetes.io/name: freshrss
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
