apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-pvc
  namespace: freshrss
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
