freshrss:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        freshrss.io/enable: 'true'
        hajimari.io/appName: freshrss
        hajimari.io/icon: rss
      hosts:
        - host: &host freshrss.kleinsorge.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: freshrss-tls-certificate
          hosts:
            - *host
