freshrss:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: rss
        hajimari.io/icon: rss
      hosts:
        - host: &host rss.kleinsorge.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: freshrss-tls-certificate
          hosts:
            - *host
  spec:
    template:
      spec:
        containers:
          ports:
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: udp
          volumeMounts:
            - name: nfs-pvc
              mountPath: /
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: nfs-client
