freshrss:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: rss
        hajimari.io/icon: rss
      hosts:
        - host: &host rss.kleinsorge.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: freshrss-tls-certificate
          hosts:
            - *host
  persistence:
    config:
      enabled: true
      type: nfs
      server: 192.168.1.208
      path: /volume1/kube/freshrss