freshrss:
  env:
    TZ: America/New_York
    PUID: 1030
    PGID: 101
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: rss
        hajimari.io/icon: rss
      hosts:
        - host: &host rss.kleinsorge.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: freshrss-tls-certificate
          hosts:
            - *host
  spec:
    template:
      spec:
        containers:
          ports:
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: udp
  persistence:
    config:
      enabled: true
      # type: nfs
      # server: 192.168.1.208
      # path: /volume1/kube/freshrss
      # # mountPath: /
