apiVersion: v2
name: argocd
version: 0.0.0
dependencies:
  - name: argo-cd
    version: 8.1.2
    repository: https://argoproj.github.io/argo-helm
  - name: argocd-apps
    version: 2.0.2
    repository: https://argoproj.github.io/argo-helm
  - name: argo-workflows
    version: 0.42.7
    repository: https://argoproj.github.io/argo-helm
  - name: argo-events
    version: 2.4.8
    repository: https://argoproj.github.io/argo-helm
