apiVersion: v1
kind: PersistentVolume
metadata: 
  name: nginx-test-data-pv
spec:
  storageClassName: ""
  capacity:
    storage: 10Gb
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.208
    path: /volume1/kube/nginx-test
