apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-test-pvc
spec:
  storageClassName: ""
  volumeName: nginx-test-pv
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
