ingress-nginx:
  controller:
    service:
      annotations:
        metallb.universe.tf/address-pool: default
    ingressClassResource:
      name: nginx
      enabled: true
      default: true
      controllerValue: "k8s.io/ingress-nginx"
    extraArgs:
      enable-ssl-passthrough: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    admissionWebhooks:
      enabled: false
      failurePolicy: Ignore
    config:
      custom-http-errors: >-
        401,403,404,500,501,502,503
  defaultBackend:
    enabled: true
    image:
      repository: ghcr.io/tarampampam/error-pages
      tag: 2.21.0
    extraEnvs:
    - name: TEMPLATE_NAME
      value: shuffle
    - name: SHOW_DETAILS # Optional: enables the output of additional information on error pages
      value: 'true'