{{- if .Values.backups.enabled }}
{{- range .Values.backups.volumes }}
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: {{ .pvc }}
  namespace: {{ .namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
    freshlab.kleinsorge.dev/backup: restic-nfs
spec:
  sourcePVC: {{ .pvc }}
  trigger:
    schedule: {{ $.Values.backups.schedule | quote }}
  restic:
    repository: {{ .pvc }}-volsync-restic
    copyMethod: {{ $.Values.backups.copyMethod }}
    pruneIntervalDays: {{ $.Values.backups.pruneIntervalDays }}
    retain:
{{ toYaml $.Values.backups.retain | indent 6 }}
{{- end }}
{{- end }}
